### ISSUE TITLE
Skipping virtually all cached items

### ISSUE THREAD

**Issue by snicoara** [MEM-Zone/MEM.Zone#13]
I'm hoping this isn't a simple mistake on my part but running this script on a device with administrative access and 35 separate items in the ccmcache results in only 2 being visible when the script is run. I have tried modifying the thresholds as I want it to be fairly aggressive in it's cleanup but it will not spot the remaining 33 items. 

No errors logged, results below:

PS C:\sparke\scripts> .\Clean-CMClientCache.ps1 -verbose
VERBOSE: [03-08-2022 16:45:11.436] [Main:Initialization] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.530] [Main:Initialization] [Clean-CMClientCache] :: Should Run test passed
VERBOSE: [03-08-2022 16:45:11.530] [Main:Initialization] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:11.546] [Remove-CCMCachedApplications] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.561] [Get-CCMCachedApplications] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.655] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:11.671] [Remove-CCMCachedApplications] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:11.682] [Remove-CCMCachedPackages] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.687] [Get-CCMCachedPackages] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.735] [Get-CCMCachedPackages] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:11.735] [Remove-CCMCachedPackages] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:11.751] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:11.751] [Get-CCMCachedUpdates] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:13.235] [Get-CCMCachedUpdates] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:13.235] [Remove-CCMCachedUpdates] [Clean-CMClientCache] :: Stop
VERBOSE: [03-08-2022 16:45:13.250] [Remove-CCMOrphanedCache] [Clean-CMClientCache] :: Start
VERBOSE: [03-08-2022 16:45:13.409] [Remove-CCMOrphanedCache] [Clean-CMClientCache] :: Stop
[03-08-2022 16:45:13.425] [Main:CleanupResult] [Clean-CMClientCache] ::

FullName          :
Name              : 5009469
Location          : C:\WINDOWS\ccmcache\1r
LastReferenceTime : 1/03/2022 2:33:08 AM
Size(MB)          :
Status            : Needed

FullName          :
Name              : 5008880
Location          : C:\WINDOWS\ccmcache\1s
LastReferenceTime : 1/03/2022 2:33:57 AM
Size(MB)          :
Status            : Needed

TotalDeletedSize: 0
VERBOSE: [03-08-2022 16:45:13.425] [Main:CleanupResult] [Clean-CMClientCache] :: Stop
PS C:\sparke\scripts>

Any idea's what may be going on here?

**Comment by Ioan-Popovici** [comment]
Merged with https://github.com/MEM-Zone/MEM.Zone/issues/7
