### ISSUE TITLE
HW BIOS Report Wont Run

### ISSUE THREAD

**Issue by Brachus12** [MEM-Zone/MEM.Zone#15]
This was even after making sure the DataSet was pointed correctly

For more information about this error navigate to the report server on the local server machine, or enable remote errors
----------------------------
Query execution failed for dataset 'ReportDescription'. (rsErrorExecutingCommand)
----------------------------
An error has occurred during report processing. (rsProcessingAborted)

**Comment by Ioan-Popovici** [comment]
Deprecated, will not fix
