### ISSUE TITLE
[BUG] Disk Cleanup stays open in the background

### ISSUE THREAD

**Issue by JonathanPitre** [MEM-Zone/MEM.Zone#17]
**Describe the bug**
Even though disk cleanup launch and run properly, it stays open forever in the background and I have to manually kill the process every single time.

Maybe a kill command could be launched after a certain wait time?

**Expected behavior**
Disk Cleanup should close automatically when done and the script should continue.

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2

**Comment by Ioan-Popovici** [comment]
I will try to run cleanmgr interactively to see what's happening.
You could do the same selecting everything from the GUI.

**Comment by JonathanPitre** [comment]
I did, it seems to get stuck on Windows Defender cleanup. If I click on the process window, it ends the process. Weird one!

**Comment by Ioan-Popovici** [comment]
I can't reproduce it in Windows 11. Please re-open if you have more info
![CleanShot 2023-07-13 at 13 01 44](https://github.com/MEM-Zone/MEM.Zone/assets/17069425/530f3088-645d-4d75-8fdf-49df601cb898)
