### ISSUE TITLE
[FEATURE] Rename-IntuneDevice Android Support

### ISSUE THREAD

**Issue by Rakib** [MEM-Zone/MEM.Zone#19]
Dedicated devices has the worst and non-descriptive names.

**Comment by Ioan-Popovici** [comment]
Please test this version:

https://github.com/MEM-Zone/MEM.Zone/tree/develop/Scripts/PowerShell/Rename-IntuneDevice

## 2.1.0b - 2024-02-02

* Added support for `Android` and `iOS/macOS` devices (Issue #19).
* Added supported devices check.
* Added `iOS/macOS` supervision check.
* Added `Warning` when a device is skipped.
* Simplified the `ForEach` loop.

**Comment by Ioan-Popovici** [comment]
Released v 2.1.1, closing issue.
