### ISSUE TITLE
[BUG] Invoke-CCMCacheCleanup 6.0.4

### ISSUE THREAD

**Issue by Life-of-Roy** [MEM-Zone/MEM.Zone#21]
**Describe the goal**
I'm looking to purge deployment folders that are no longer active from CCMCache. I have tried the following two methods on how I understand I can achieve my goal but I did not get the results I was expecting.

**To Reproduce**
==Example 1==
.\Invoke-CCMCacheCleanup.ps1 -CacheType "Orphaned" -CleanupType "Automatic" -LoggingOptions File -LogDebugMessages -LogName "Invoke-CCMCacheCleanup"

Result: Executed the code which displayed the status bar but completed with 'Total Deleted: 0 B'. Using Right Click Tools I am able to review that there all existing orphan folders (34 in total) remain.

==Example 2==
.\Invoke-CCMCacheCleanup.ps1 -CacheType "All" -CleanupType "Tombstoned" -LoggingOptions File -LogDebugMessages -LogName "Invoke-CCMCacheCleanup"

Result: No status bar was displayed with execution the line. The log file that was generated provided the following line:
[Main:Initialization] :: Should Run test failed.

**Screenshots**
https://i.postimg.cc/43B4q5VW/Orphans-1.jpg
https://i.postimg.cc/nzrVJD1p/Orphans-2.jpg

**Desktop**
 - OS: Windows 11

**Comment by Ioan-Popovici** [comment]
I'll explain in detail on how the cleanup works, it's possible I might need to shuffle some parameters around I need to see if I accounted for this specific scenario or not.

But definitely if you didn't understand the blog post immediately it needs to be clarified and expanded.

The orphaned cache is definitely a bug. What the script does it looks at the cache folder and tries to match the WMI registry and vice-versa. If something is on disk and not in WMI or is in WMI and not on the disk the cache is tagged as orphaned. I don't know how rightclick tools finds orpycache but I'll look into it.

**Comment by Ioan-Popovici** [comment]
Fixed in [v7.0.0](https://MEMZ.one/Invoke-CCMCacheCleanup-GIT), thanks!
