### ISSUE TITLE
Error On Line 831 - When No User Has Logged Onto Device

### ISSUE THREAD

**Issue by SCCMWalker** [MEM-Zone/MEM.Zone#8]
Howdy Ioan,

I found an issue if you have no users that have logged onto the device yet, at least in my environment, you get an error when trying to populate the $Packages variable. The error is a generic failure when trying to access the namespace. I would suggest adding ErrorAction SilentlyContinue to that line as so. I will try to attach the full error if I can get to it.
$Packages = Get-CimInstance -Namespace 'Root\ccm\ClientSDK' -ClassName 'CCM_Program' -Verbose:$false -ErrorAction SilenetlyContinue

**Comment by Ioan-Popovici** [comment]
# Invoke-CCMCacheCleanup release history

## 6.0.0 - 2023-07-28

* [Breaking] Completely rewritten, functionality has changed
* [Breaking] Renamed `CleanupActions` to `CacheType`
* [Breaking] Added `CleanupType` parameter with `Automatic` mode for cache cleanup
* Fixed [Get-CimInstance : Invalid class](https://github.com/MEM-Zone/MEM.Zone/issues/14) @idrositis
* Fixed [Error On Line 831](https://github.com/MEM-Zone/MEM.Zone/issues/8) @SCCMWalker
* Fixed [Not detecting or removing most content](https://github.com/MEM-Zone/MEM.Zone/issues/7) @PhilAitman
* Added a lot of optimizations under the hood
